# .gitlab-ci.yml for Python/Terraform project using uv
stages:
  - lint
  - test
  - validate

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.uv_cache"

before_script:
  - uv --version
  - uv pip install -e .[dev]

lint:
  stage: lint
  script:
    - ruff .
    - black --check .
    - mypy .

pytest:
  stage: test
  script:
    - pytest

terraform-validate:
  stage: validate
  script:
    - terraform init -backend=false
    - terraform validate
  rules:
    - exists:
        - bedrock_agentic_ds_team.tf
        - gcp_agentic_ds_team.tf
