# GitHub Actions CI for Python and Terraform, and CD for AWS/GCP
name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Python & Terraform CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          uv pip install -e .[dev]

      - name: Lint Python
        run: |
          ruff .
          black --check .
          mypy .

      - name: Test Python (if tests exist)
        run: |
          if [ -d tests ]; then pytest; fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init

      - name: Terraform validate (AWS)
        run: terraform validate
        working-directory: .

      - name: Terraform validate (GCP)
        run: terraform validate
        working-directory: ./modules/gcp_agentic_ds_team

  cd:
    name: Deploy to Cloud (AWS or GCP)
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials
        if: ${{ contains(github.event.head_commit.modified, 'bedrock_agentic_ds_team') || contains(github.event.head_commit.modified, 'modules/bedrock_agentic_ds_team') }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS (Terraform apply)
        if: ${{ contains(github.event.head_commit.modified, 'bedrock_agentic_ds_team') || contains(github.event.head_commit.modified, 'modules/bedrock_agentic_ds_team') }}
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: .

      - name: Set up Google Cloud
        if: ${{ contains(github.event.head_commit.modified, 'gcp_agentic_ds_team') || contains(github.event.head_commit.modified, 'modules/gcp_agentic_ds_team') }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set up gcloud CLI
        if: ${{ contains(github.event.head_commit.modified, 'gcp_agentic_ds_team') || contains(github.event.head_commit.modified, 'modules/gcp_agentic_ds_team') }}
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GCP (Terraform apply)
        if: ${{ contains(github.event.head_commit.modified, 'gcp_agentic_ds_team') || contains(github.event.head_commit.modified, 'modules/gcp_agentic_ds_team') }}
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: .
